/*
    FileName: party_winrisk_rel_agreement_nb_requirements.sql
    Author: MM69917	
    Subject Area : Party
    Source: TPP
    Create Date:2021-11-22
       
    ===============================================================================================================
    Version/JIRA Story#     Created By     Last_Modified_Date   Description
    ---------------------------------------------------------------------------------------------------------------
    TERSUN-3702             Party-Tier2    11/22                Initial version      
    ------------------------------------------------------------------------------------------------------------------
*/

SELECT ANALYZE_STATISTICS('PROD_NBR_VW_TERSUN.NB_REQ_VW');
SELECT ANALYZE_STATISTICS('PROD_NBR_VW_TERSUN.NB_APPL_VW');

CREATE LOCAL TEMPORARY TABLE VT_NB_APPL ON COMMIT PRESERVE ROWS AS 
/* +DIRECT */
SELECT appl_id, hldg_key, hldg_key_pfx, hldg_key_sfx, carr_admin_sys_cd, cas_id 
FROM (
SELECT appl_id, 
clean_string(hldg_key) as hldg_key, 
clean_string(hldg_key_pfx) as hldg_key_pfx, 
clean_string(hldg_key_sfx) as hldg_key_sfx, 
clean_string(carr_admin_sys_cd) as carr_admin_sys_cd,
cas_id as cas_id,
row_number() over(partition by appl_id order by appl_data_fr_dt desc) as rnk
FROM prod_nbr_vw_tersun.NB_APPL_VW
)dedup
WHERE RNK=1
ORDER BY appl_id;

CREATE LOCAL TEMPORARY TABLE VT_SRC ON COMMIT PRESERVE ROWS AS 
/* +DIRECT */
SELECT 
APPL_ID AS APPL_ID,
CASE WHEN CLEAN_STRING(src.REQ_CD) = 'Fnlsutvl' THEN 'Fnlsutvld'
     WHEN CLEAN_STRING(src.REQ_CD) = 'Dighlthp' THEN 'Dighlthpro'
     WHEN CLEAN_STRING(src.REQ_CD) = 'Intsutvl' THEN 'Intsutvld'
     WHEN CLEAN_STRING(src.REQ_CD) = 'Sulreplr' THEN 'Sulreplrew'
     WHEN CLEAN_STRING(src.REQ_CD) IS NULL THEN 'Unk'
     ELSE CLEAN_STRING(src.REQ_CD) END AS REQ_CD, 
CLEAN_STRING(src.CAS_REQ_ID)      AS CAS_REQ_ID,
CLEAN_STRING(src.REQ_COLL_METH)   AS REQ_COLL_METH,
CLEAN_STRING(src.REQ_CTG)         AS REQ_CTG,
CLEAN_STRING(VOLTAGEACCESS(src.REQ_CMNT,'freeform'))        AS REQ_CMNT,
CLEAN_STRING(src.REQ_STUS_CD)     AS REQ_STUS_CD,
CLEAN_STRING(src.SRC_REQ_STUS_CD) AS SRC_REQ_STUS_CD,
src.REQ_ORDR_DT::DATE             AS REQ_ORDR_DT, 
CLEAN_STRING(src.SRC_WRKBNCH_COLL_ID)   AS SRC_WRKBNCH_COLL_ID,
CLEAN_STRING(src.WRKBNCH_COLL_METH)     AS WRKBNCH_COLL_METH,
CLEAN_STRING(src.PHY_NM)          AS PHY_NM,  -- PII 
CLEAN_STRING(src.SRC_REQ_ID)      AS SRC_REQ_ID, 
src.REQ_STUS_DT::DATE             AS REQ_STUS_DT,
CLEAN_STRING(src.SRC_REQ_CTG)     AS SRC_REQ_CTG,
src.REQ_FR_DT                     AS REQ_FR_DT,
src.REQ_TO_DT                     AS REQ_TO_DT,
CLEAN_STRING(src.SRC_DEL_IND)     AS SRC_DEL_IND  
FROM prod_nbr_vw_tersun.NB_REQ_VW src
WHERE src_sys_id ='36'; --13mins

CREATE LOCAL TEMPORARY TABLE VT_FINAL_SRC ON COMMIT PRESERVE ROWS AS 
/* +DIRECT */
SELECT 
LPAD(appl.HLDG_KEY,20,'0')  AS HLDG_KEY,
appl.HLDG_KEY_PFX           AS HLDG_KEY_PFX,
appl.HLDG_KEY_SFX           AS HLDG_KEY_SFX,
COALESCE(appl.CARR_ADMIN_SYS_CD,'Unk')   AS CARR_ADMIN_SYS_CD,
appl.CAS_ID::VARCHAR(50)    AS CAS_ID,
src.REQ_CD             AS REQ_CD,
src.CAS_REQ_ID         AS CAS_REQ_ID,
src.REQ_COLL_METH      AS REQ_COLL_METH,
src.REQ_CTG            AS REQ_CTG,
SUBSTRING(src.REQ_CMNT,1,500)           AS REQ_CMNT,
src.REQ_STUS_CD        AS REQ_STUS_CD,
src.SRC_REQ_STUS_CD    AS SRC_REQ_STUS_CD,
src.REQ_ORDR_DT        AS REQ_ORDR_DT, 
src.SRC_WRKBNCH_COLL_ID   AS SRC_WRKBNCH_COLL_ID,
src.WRKBNCH_COLL_METH     AS WRKBNCH_COLL_METH,
src.PHY_NM                AS PHY_NM,  -- PII 
src.SRC_REQ_ID            AS SRC_REQ_ID, 
src.REQ_STUS_DT           AS REQ_STUS_DT,
src.SRC_REQ_CTG           AS SRC_REQ_CTG,
src.REQ_FR_DT             AS REQ_FR_DT,
src.REQ_TO_DT             AS REQ_TO_DT,
src.SRC_DEL_IND           AS SRC_DEL_IND 
FROM VT_SRC src
LEFT JOIN VT_NB_APPL appl 
ON src.APPL_ID = appl.APPL_ID;

COMMIT;

CREATE LOCAL TEMPORARY TABLE VT_PRE_WORK ON COMMIT PRESERVE ROWS AS 
SELECT * FROM EDW.REL_AGREEMENT_NB_REQUIREMENT 
WHERE 1<>1;

INSERT /* +DIRECT */  INTO VT_PRE_WORK
(
    DIM_AGREEMENT_NATURAL_KEY_HASH_UUID,
    REF_REQUIREMENT_TYPE_NATURAL_KEY_HASH_UUID,
    REQUIREMENT_CASE_ID,
    COLLECTION_METHORD_CDE,
    REQUIREMENT_CATEGORY_CDE,
    REQUIREMENT_COMMENT_TXT,
    REQUIREMENT_STATUS_CDE,
    SOURCE_REQUIREMENT_STATUS_CDE,
    REQUIREMENT_ORDER_DT,
    WORKBENCH_COLLECTION_ID,
    WORKBENCH_COLLECTION_METHORD_CDE,
    PHYSICIAN_FULL_NM,
    SOURCE_REQUIREMENT_CDE,
    REQUIREMENT_STATUS_DT,
    SOURCE_REQUIREMENT_CATEGORY, 
    BEGIN_DT,
    BEGIN_DTM,
    ROW_PROCESS_DTM,
    AUDIT_ID,
    LOGICAL_DELETE_IND,
    CHECK_SUM,
    CURRENT_ROW_IND,
    END_DT,
    END_DTM,
    SOURCE_SYSTEM_ID,
    RESTRICTED_ROW_IND,
    UPDATE_AUDIT_ID,
    SOURCE_DELETE_IND
)
SELECT 
    DIM_AGREEMENT_NATURAL_KEY_HASH_UUID,
    REF_REQUIREMENT_TYPE_NATURAL_KEY_HASH_UUID,
    REQUIREMENT_CASE_ID,
    COLLECTION_METHORD_CDE,
    REQUIREMENT_CATEGORY_CDE,
    REQUIREMENT_COMMENT_TXT,
    REQUIREMENT_STATUS_CDE,
    SOURCE_REQUIREMENT_STATUS_CDE,
    REQUIREMENT_ORDER_DT,
    WORKBENCH_COLLECTION_ID,
    WORKBENCH_COLLECTION_METHORD_CDE,
    PHYSICIAN_FULL_NM,
    SOURCE_REQUIREMENT_CDE,
    REQUIREMENT_STATUS_DT,
    SOURCE_REQUIREMENT_CATEGORY, 
    BEGIN_DT,
    BEGIN_DTM,
    ROW_PROCESS_DTM,
    AUDIT_ID,
    LOGICAL_DELETE_IND,
    CHECK_SUM,
    CURRENT_ROW_IND,
    END_DT,
    END_DTM,
    SOURCE_SYSTEM_ID,
    RESTRICTED_ROW_IND,
    UPDATE_AUDIT_ID,
    SOURCE_DELETE_IND
FROM 
(
SELECT 
    DIM_AGREEMENT_NATURAL_KEY_HASH_UUID,
    REF_REQUIREMENT_TYPE_NATURAL_KEY_HASH_UUID,
    REQUIREMENT_CASE_ID,
    COLLECTION_METHORD_CDE,
    REQUIREMENT_CATEGORY_CDE,
    REQUIREMENT_COMMENT_TXT,
    REQUIREMENT_STATUS_CDE,
    SOURCE_REQUIREMENT_STATUS_CDE,
    REQUIREMENT_ORDER_DT,
    WORKBENCH_COLLECTION_ID,
    WORKBENCH_COLLECTION_METHORD_CDE,
    PHYSICIAN_FULL_NM,
    SOURCE_REQUIREMENT_CDE,
    REQUIREMENT_STATUS_DT,
    SOURCE_REQUIREMENT_CATEGORY, 
    BEGIN_DT,
    BEGIN_DTM,
    ROW_PROCESS_DTM,
    AUDIT_ID,
    LOGICAL_DELETE_IND,
    UUID_GEN(SOURCE_DELETE_IND, COLLECTION_METHORD_CDE, REQUIREMENT_CATEGORY_CDE,REQUIREMENT_COMMENT_TXT,REQUIREMENT_STATUS_CDE, SOURCE_REQUIREMENT_STATUS_CDE, 
             REQUIREMENT_ORDER_DT, WORKBENCH_COLLECTION_ID, WORKBENCH_COLLECTION_METHORD_CDE, PHYSICIAN_FULL_NM, SOURCE_REQUIREMENT_CDE, REQUIREMENT_STATUS_DT,
             SOURCE_REQUIREMENT_CATEGORY )::UUID AS CHECK_SUM,
    CURRENT_ROW_IND,
    END_DT,
    END_DTM,
    SOURCE_SYSTEM_ID,
    RESTRICTED_ROW_IND,
    UPDATE_AUDIT_ID,
    SOURCE_DELETE_IND,
    ROW_NUMBER() OVER (PARTITION BY DIM_AGREEMENT_NATURAL_KEY_HASH_UUID, REF_REQUIREMENT_TYPE_NATURAL_KEY_HASH_UUID, REQUIREMENT_CASE_ID, COLLECTION_METHORD_CDE, 
                                    REQUIREMENT_CATEGORY_CDE, REQUIREMENT_COMMENT_TXT,REQUIREMENT_STATUS_CDE, SOURCE_REQUIREMENT_STATUS_CDE, REQUIREMENT_ORDER_DT,
                                    WORKBENCH_COLLECTION_ID, WORKBENCH_COLLECTION_METHORD_CDE, PHYSICIAN_FULL_NM, SOURCE_REQUIREMENT_CDE, REQUIREMENT_STATUS_DT,
                                    SOURCE_REQUIREMENT_CATEGORY
                       ORDER BY BEGIN_DT DESC, END_DT DESC) AS RNK 
FROM
(
SELECT 
    CASE WHEN (CARR_ADMIN_SYS_CD, HLDG_KEY_PFX, HLDG_KEY, HLDG_KEY_SFX) IS NULL 
         THEN UUID_GEN(NULL)::UUID 
         ELSE UUID_GEN(CARR_ADMIN_SYS_CD, 'Appl', HLDG_KEY_PFX, HLDG_KEY, HLDG_KEY_SFX, '0')::UUID 
         END AS DIM_AGREEMENT_NATURAL_KEY_HASH_UUID, 
    UUID_GEN(REQ_CD)::UUID     AS REF_REQUIREMENT_TYPE_NATURAL_KEY_HASH_UUID,
    CAS_REQ_ID                 AS REQUIREMENT_CASE_ID,
    REQ_COLL_METH              AS COLLECTION_METHORD_CDE,
    REQ_CTG                    AS REQUIREMENT_CATEGORY_CDE,
    VOLTAGEPROTECT(REQ_CMNT,'freeform')  AS REQUIREMENT_COMMENT_TXT,
    REQ_STUS_CD                AS REQUIREMENT_STATUS_CDE,
    SRC_REQ_STUS_CD            AS SOURCE_REQUIREMENT_STATUS_CDE,
    REQ_ORDR_DT                AS REQUIREMENT_ORDER_DT,
    SRC_WRKBNCH_COLL_ID        AS WORKBENCH_COLLECTION_ID,
    WRKBNCH_COLL_METH          AS WORKBENCH_COLLECTION_METHORD_CDE,
    VOLTAGEPROTECT(PHY_NM,'name')        AS PHYSICIAN_FULL_NM,
    SRC_REQ_ID                 AS SOURCE_REQUIREMENT_CDE,
    REQ_STUS_DT                AS REQUIREMENT_STATUS_DT,
    SRC_REQ_CTG                AS SOURCE_REQUIREMENT_CATEGORY,
    REQ_FR_DT::DATE            AS BEGIN_DT,
    REQ_FR_DT::TIMESTAMP(6)    AS BEGIN_DTM,
    CURRENT_TIMESTAMP(6)       AS ROW_PROCESS_DTM,
    :audit_id                  AS AUDIT_ID,
    FALSE::BOOLEAN             AS LOGICAL_DELETE_IND,
    CASE WHEN REQ_TO_DT::DATE='12-31-9999' THEN TRUE ELSE FALSE END AS CURRENT_ROW_IND,
    REQ_TO_DT::DATE            AS END_DT,
    REQ_TO_DT::TIMESTAMP(6)    AS END_DTM,
    '324'                      AS SOURCE_SYSTEM_ID,
    FALSE::BOOLEAN             AS RESTRICTED_ROW_IND,
    :audit_id                  AS UPDATE_AUDIT_ID,
    CASE WHEN SRC_DEL_IND='Y' THEN TRUE ELSE FALSE END AS SOURCE_DELETE_IND
FROM VT_FINAL_SRC
)CLEANSED_DATASET
)DEDUP 
WHERE RNK=1;

CREATE LOCAL TEMPORARY TABLE VT_ORDER_BY ON COMMIT PRESERVE ROWS AS 
SELECT *, ROW_NUMBER() OVER(PARTITION BY DIM_AGREEMENT_NATURAL_KEY_HASH_UUID, REF_REQUIREMENT_TYPE_NATURAL_KEY_HASH_UUID, REQUIREMENT_CASE_ID
                            ORDER BY END_DTM DESC, BEGIN_DTM DESC) AS RW_NUM 
FROM VT_PRE_WORK
ORDER BY DIM_AGREEMENT_NATURAL_KEY_HASH_UUID, 
REF_REQUIREMENT_TYPE_NATURAL_KEY_HASH_UUID, 
REQUIREMENT_CASE_ID,
END_DTM,
BEGIN_DTM;

TRUNCATE TABLE EDW_WORK.PARTY_WINRISK_REL_AGREEMENT_NB_REQUIREMENT;

INSERT INTO EDW_WORK.PARTY_WINRISK_REL_AGREEMENT_NB_REQUIREMENT
(
    DIM_AGREEMENT_NATURAL_KEY_HASH_UUID,
    REF_REQUIREMENT_TYPE_NATURAL_KEY_HASH_UUID,
    REQUIREMENT_CASE_ID,
    COLLECTION_METHORD_CDE,
    REQUIREMENT_CATEGORY_CDE,
    REQUIREMENT_COMMENT_TXT,
    REQUIREMENT_STATUS_CDE,
    SOURCE_REQUIREMENT_STATUS_CDE,
    REQUIREMENT_ORDER_DT,
    WORKBENCH_COLLECTION_ID,
    WORKBENCH_COLLECTION_METHORD_CDE,
    PHYSICIAN_FULL_NM,
    SOURCE_REQUIREMENT_CDE,
    REQUIREMENT_STATUS_DT,
    SOURCE_REQUIREMENT_CATEGORY, 
    BEGIN_DT,
    BEGIN_DTM,
    ROW_PROCESS_DTM,
    AUDIT_ID,
    LOGICAL_DELETE_IND,
    CHECK_SUM,
    CURRENT_ROW_IND,
    END_DT,
    END_DTM,
    SOURCE_SYSTEM_ID,
    RESTRICTED_ROW_IND,
    UPDATE_AUDIT_ID,
    SOURCE_DELETE_IND
)
SELECT 
    A.DIM_AGREEMENT_NATURAL_KEY_HASH_UUID,
    A.REF_REQUIREMENT_TYPE_NATURAL_KEY_HASH_UUID,
    A.REQUIREMENT_CASE_ID,
    A.COLLECTION_METHORD_CDE,
    A.REQUIREMENT_CATEGORY_CDE,
    A.REQUIREMENT_COMMENT_TXT,
    A.REQUIREMENT_STATUS_CDE,
    A.SOURCE_REQUIREMENT_STATUS_CDE,
    A.REQUIREMENT_ORDER_DT,
    A.WORKBENCH_COLLECTION_ID,
    A.WORKBENCH_COLLECTION_METHORD_CDE,
    A.PHYSICIAN_FULL_NM,
    A.SOURCE_REQUIREMENT_CDE,
    A.REQUIREMENT_STATUS_DT,
    A.SOURCE_REQUIREMENT_CATEGORY, 
    A.BEGIN_DT,
    A.BEGIN_DTM,
    A.ROW_PROCESS_DTM,
    A.AUDIT_ID,
    A.LOGICAL_DELETE_IND,
    A.CHECK_SUM,
    CASE WHEN A.RW_NUM > B.RW_NUM AND B.RW_NUM = A.RW_NUM-1 AND A.CURRENT_ROW_IND=TRUE THEN FALSE ELSE A.CURRENT_ROW_IND END AS CURRENT_ROW_IND,
    CASE WHEN A.RW_NUM>B.RW_NUM AND B.RW_NUM=A.RW_NUM-1 AND A.CURRENT_ROW_IND=TRUE THEN B.BEGIN_DT - INTERVAL '1' DAY 
         WHEN A.RW_NUM=1 AND A.CURRENT_ROW_IND=TRUE AND A.END_DT<>'9999-12-31' THEN '9999-12-31'::DATE
         ELSE A.END_DT END AS END_DT,
    CASE WHEN A.RW_NUM>B.RW_NUM AND B.RW_NUM=A.RW_NUM-1 AND A.CURRENT_ROW_IND=TRUE THEN B.BEGIN_DTM - INTERVAL '1' SECOND 
         WHEN A.RW_NUM=1 AND A.CURRENT_ROW_IND=TRUE AND A.END_DT<>'9999-12-31' THEN '9999-12-31'::TIMESTAMP(6)
         ELSE A.END_DTM END AS END_DTM, 
    A.SOURCE_SYSTEM_ID,
    A.RESTRICTED_ROW_IND,
    A.UPDATE_AUDIT_ID,
    A.SOURCE_DELETE_IND
FROM VT_ORDER_BY A 
LEFT JOIN VT_ORDER_BY B 
ON A.DIM_AGREEMENT_NATURAL_KEY_HASH_UUID = B.DIM_AGREEMENT_NATURAL_KEY_HASH_UUID
AND A.REF_REQUIREMENT_TYPE_NATURAL_KEY_HASH_UUID = B.REF_REQUIREMENT_TYPE_NATURAL_KEY_HASH_UUID
AND COALESCE(A.REQUIREMENT_CASE_ID,'-') = COALESCE(B.REQUIREMENT_CASE_ID,'-')
AND A.RW_NUM = B.RW_NUM+1;

DELETE FROM EDW.REL_AGREEMENT_NB_REQUIREMENT WHERE SOURCE_SYSTEM_ID IN ('324','36');

INSERT INTO EDW.REL_AGREEMENT_NB_REQUIREMENT 
(
    DIM_AGREEMENT_NATURAL_KEY_HASH_UUID,
    REF_REQUIREMENT_TYPE_NATURAL_KEY_HASH_UUID,
    REQUIREMENT_CASE_ID,
    COLLECTION_METHORD_CDE,
    REQUIREMENT_CATEGORY_CDE,
    REQUIREMENT_COMMENT_TXT,
    REQUIREMENT_STATUS_CDE,
    SOURCE_REQUIREMENT_STATUS_CDE,
    REQUIREMENT_ORDER_DT,
    WORKBENCH_COLLECTION_ID,
    WORKBENCH_COLLECTION_METHORD_CDE,
    PHYSICIAN_FULL_NM,
    SOURCE_REQUIREMENT_CDE,
    REQUIREMENT_STATUS_DT,
    SOURCE_REQUIREMENT_CATEGORY, 
    BEGIN_DT,
    BEGIN_DTM,
    ROW_PROCESS_DTM,
    AUDIT_ID,
    LOGICAL_DELETE_IND,
    CHECK_SUM,
    CURRENT_ROW_IND,
    END_DT,
    END_DTM,
    SOURCE_SYSTEM_ID,
    RESTRICTED_ROW_IND,
    UPDATE_AUDIT_ID,
    SOURCE_DELETE_IND
)
SELECT 
    DIM_AGREEMENT_NATURAL_KEY_HASH_UUID,
    REF_REQUIREMENT_TYPE_NATURAL_KEY_HASH_UUID,
    REQUIREMENT_CASE_ID,
    COLLECTION_METHORD_CDE,
    REQUIREMENT_CATEGORY_CDE,
    REQUIREMENT_COMMENT_TXT,
    REQUIREMENT_STATUS_CDE,
    SOURCE_REQUIREMENT_STATUS_CDE,
    REQUIREMENT_ORDER_DT,
    WORKBENCH_COLLECTION_ID,
    WORKBENCH_COLLECTION_METHORD_CDE,
    PHYSICIAN_FULL_NM,
    SOURCE_REQUIREMENT_CDE,
    REQUIREMENT_STATUS_DT,
    SOURCE_REQUIREMENT_CATEGORY, 
    BEGIN_DT,
    BEGIN_DTM,
    ROW_PROCESS_DTM,
    AUDIT_ID,
    LOGICAL_DELETE_IND,
    CHECK_SUM,
    CURRENT_ROW_IND,
    END_DT,
    END_DTM,
    SOURCE_SYSTEM_ID,
    RESTRICTED_ROW_IND,
    UPDATE_AUDIT_ID,
    SOURCE_DELETE_IND
FROM EDW_WORK.PARTY_WINRISK_REL_AGREEMENT_NB_REQUIREMENT;

COMMIT;