DROP TABLE IF EXISTS APPL_VW;

CREATE LOCAL TEMPORARY TABLE APPL_VW ON COMMIT PRESERVE ROWS AS
/*DIRECT*/
SELECT APPL_ID,CASE_ID,POLICY_NUMBER from 
(SELECT 
APPL_ID AS APPL_ID,
CAS_ID AS CASE_ID,
CLEAN_STRING(HLDG_KEY) AS POLICY_NUMBER,
ROW_NUMBER () OVER(PARTITION BY APPL_ID ORDER BY APPL_DATA_FR_DT  DESC) AS RNK
FROM PROD_NBR_VW_TERSUN.NB_APPL_VW WHERE SRC_SYS_ID='77'
)Q_1
WHERE RNK=1;




TRUNCATE TABLE EDW_STAGING.DI_DIPMS_EDW_DIPMS_PARTY_CASE_OWNER_SNAPSHOT;


INSERT /*DIRECT*/ INTO EDW_STAGING.DI_DIPMS_EDW_DIPMS_PARTY_CASE_OWNER_SNAPSHOT(
	POLICY_NUMBER,
    CASE_ID,
    AGREEMENT_NB_SOURCE,
    LAST_NAME,
    FIRST_NAME,
    LOGINID,
    TEAM_ID,
    ROLE_CD,
    CHANGE_MODE,
    LST_UPDT_DT,
    _EDAP_SOURCE_FILE_PATH,
    _EDAP_LOAD_TIME,
    ROW_PROCESS_DTM,
    AUDIT_ID,
    SOURCE_SYSTEM_ID,
    CURRENT_BATCH 
)
SELECT 
	POLICY_NUMBER,
    CASE_ID,
    AGREEMENT_NB_SOURCE,
    LAST_NAME,
    FIRST_NAME,
    LOGINID,
    TEAM_ID,
    ROLE_CD,
    CHANGE_MODE,
    LST_UPDT_DT,
    _EDAP_SOURCE_FILE_PATH,
    _EDAP_LOAD_TIME,
    ROW_PROCESS_DTM,
    AUDIT_ID,
    SOURCE_SYSTEM_ID,
    CURRENT_BATCH 
    FROM(
SELECT 
	POLICY_NUMBER,
    CASE_ID,
    AGREEMENT_NB_SOURCE,
    LAST_NAME,
    FIRST_NAME,
    LOGINID,
    NULL AS TEAM_ID,
    ROLE_CD,
    CHANGE_MODE,
    LST_UPDT_DT,
    NULL AS _EDAP_SOURCE_FILE_PATH,
    NULL AS _EDAP_LOAD_TIME,
    CURRENT_TIMESTAMP(6) AS  ROW_PROCESS_DTM,
    -1 AS AUDIT_ID,
    '342' AS SOURCE_SYSTEM_ID,
    TRUE AS CURRENT_BATCH ,
	ROW_NUMBER() OVER(PARTITION BY POLICY_NUMBER,CASE_ID ORDER BY LST_UPDT_DT DESC) AS RNK
    FROM(
	SELECT 
		appl.POLICY_NUMBER::varchar(40) AS POLICY_NUMBER,
		appl.CASE_ID ::varchar(9)      AS CASE_ID,
		'DIPMS' AS AGREEMENT_NB_SOURCE,
		req.LST_NM AS LAST_NAME,
		req.FRST_NM AS FIRST_NAME,
		req.LOG_IN_ID AS LOGINID,
		req.SRC_ROLE_CD AS ROLE_CD,
		CASE WHEN CLEAN_STRING(req.SRC_DEL_IND) = 'Y' THEN 'DELETE' ELSE 'INSERT' END AS CHANGE_MODE,
		req.CASE_OWN_FR_DT::varchar(23) AS LST_UPDT_DT 
		FROM PROD_NBR_VW_TERSUN.NB_PRTY_CASE_OWN_VW req
		LEFT JOIN 
		APPL_VW appl
		on req.APPL_ID=appl.APPL_ID WHERE req.SRC_SYS_ID=77
	)Q_1
	)Q_2
WHERE RNK=1;

COMMIT;
