/*
    FileName: pdcr_rel_rel_party_agreement.sql
    Author: 
    Subject Area : Party
    Source: PDCR_REL
    Create Date:2021-11-15
       
    ===============================================================================================================
    Version/JIRA Story#     Created By     Last_Modified_Date   Description
    ---------------------------------------------------------------------------------------------------------------
    TERSUN-3418             Party-Tier2    11/15                Added delete logic   
    ------------------------------------------------------------------------------------------------------------------
*/

/* ----STATISTICS ON THE BASE SOURCE TABLES FOR PERFORMANCE */
SELECT ANALYZE_STATISTICS('EDW_STAGING.PDCR_REL_EDW_TD_SVCAGY');
SELECT ANALYZE_STATISTICS('EDW_STAGING.PDCR_REL_EDW_TD_PDCR_AGRL');

/* TRUNCATE PRE WORK TABLE AND WORK TABLE */ 

TRUNCATE TABLE EDW_STAGING.PDCR_REL_REL_PARTY_AGREEMENT_PRE_WORK;

TRUNCATE TABLE EDW_WORK.PDCR_REL_REL_PARTY_AGREEMENT;

---------***********1. Loading staging data from PDCR_REL_EDW_TD_PDCR_AGRL & PDCR_REL_EDW_TD_PDCR_AGRL----------
DROP TABLE IF EXISTS TEMP_PDCR_REL_REL_PARTY_AGREEMENT ;

CREATE LOCAL TEMPORARY TABLE TEMP_PDCR_REL_REL_PARTY_AGREEMENT ON COMMIT PRESERVE ROWS AS   
	SELECT 
	carr_admn_sys_cd,
	DIM_AGREEMENT_NATURAL_KEY_HASH_UUID, 
	DIM_PARTY_NATURAL_KEY_HASH_UUID, 
	REF_PARTY_ROLE_NATURAL_KEY_HASH_UUID, 
	REF_PARTY_SUB_ROLE_NATURAL_KEY_HASH_UUID, 
	DIM_ACCOUNT_NATURAL_KEY_HASH_UUID, 
	BEGIN_DT, 
	BEGIN_DTM, 
	ROW_PROCESS_DTM, 
	--AUDIT_ID, 
	LOGICAL_DELETE_IND, 
	CHECK_SUM, 
	CURRENT_ROW_IND, 
	END_DT, 
	END_DTM, 
	SOURCE_SYSTEM_ID, 
	RESTRICTED_ROW_IND, 
	--UPDATE_AUDIT_ID, 
	DIM_ADDRESS_NATURAL_KEY_HASH_UUID, 
	ADDRESS_TYPE_CDE, 
	ATTENTION_LINE_TXT, 
	DIM_PHONE_NATURAL_KEY_HASH_UUID, 
	DIM_ELECTRONIC_ADDRESS_NATURAL_KEY_HASH_UUID, 
	DIM_PARTY_AKA_NAME_NATURAL_KEY_HASH_UUID, 
	ADVISOR_DIM_SELLING_AGREEMENT_NATURAL_KEY_HASH_UUID,
	FIRM_DIM_SELLING_AGREEMENT_NATURAL_KEY_HASH_UUID,
	AGENCY_DIM_PARTY_NATURAL_KEY_HASH_UUID,
	SOURCE_PARTY_ROLE_CDE, 
	SOURCE_PARTY_SUB_ROLE_CDE, 
	SOURCE_ADDRESS_TYPE_CDE, 
	SOURCE_DELETE_IND, 
	BENEFICIARY_ISS_PER_STIRPES_CDE, 
	BUSINESS_STRT_DT, 
	BUSINESS_END_DT,
	DISTRIBUTOR_DIM_PARTY_NATURAL_KEY_HASH_UUID
	--operator_ind 
	FROM
	(
		SELECT 
		carr_admn_sys_cd,
		CASE WHEN (CLEAN_STRING(CARR_ADMN_SYS_CD),
		IPA,
		CLEAN_STRING(HLDG_KEY_PFX),
		CLEAN_STRING(HLDG_KEY),
		CLEAN_STRING(HLDG_KEY_SFX)) IS NOT NULL THEN 
		UUID_GEN(CLEAN_STRING(CARR_ADMN_SYS_CD),
		IPA,
		CLEAN_STRING(HLDG_KEY_PFX),
		CLEAN_STRING(HLDG_KEY),
		CLEAN_STRING(HLDG_KEY_SFX))::UUID ELSE 
		UUID_GEN(NULL)::UUID END					AS DIM_AGREEMENT_NATURAL_KEY_HASH_UUID,  
		DIM_PARTY_NATURAL_KEY_HASH_UUID, 
		REF_PARTY_ROLE_NATURAL_KEY_HASH_UUID, 
		REF_PARTY_SUB_ROLE_NATURAL_KEY_HASH_UUID, 
		DIM_ACCOUNT_NATURAL_KEY_HASH_UUID, 
		BEGIN_DT, 
		BEGIN_DTM, 
		ROW_PROCESS_DTM, 
		--AUDIT_ID, 
		LOGICAL_DELETE_IND, 
		UUID_GEN(SOURCE_DELETE_IND,SOURCE_PARTY_ROLE_CDE,SOURCE_PARTY_SUB_ROLE_CDE)::UUID AS CHECK_SUM,
		CURRENT_ROW_IND, 
		END_DT, 
		END_DTM, 
		SOURCE_SYSTEM_ID, 
		RESTRICTED_ROW_IND, 
		--UPDATE_AUDIT_ID, 
		DIM_ADDRESS_NATURAL_KEY_HASH_UUID, 
		ADDRESS_TYPE_CDE, 
		ATTENTION_LINE_TXT, 
		DIM_PHONE_NATURAL_KEY_HASH_UUID, 
		DIM_ELECTRONIC_ADDRESS_NATURAL_KEY_HASH_UUID, 
		DIM_PARTY_AKA_NAME_NATURAL_KEY_HASH_UUID, 
		ADVISOR_DIM_SELLING_AGREEMENT_NATURAL_KEY_HASH_UUID,
		FIRM_DIM_SELLING_AGREEMENT_NATURAL_KEY_HASH_UUID,
		AGENCY_DIM_PARTY_NATURAL_KEY_HASH_UUID,
		SOURCE_PARTY_ROLE_CDE, 
		SOURCE_PARTY_SUB_ROLE_CDE, 
		SOURCE_ADDRESS_TYPE_CDE, 
		SOURCE_DELETE_IND, 
		BENEFICIARY_ISS_PER_STIRPES_CDE, 
		BUSINESS_STRT_DT, 
		BUSINESS_END_DT,
		DISTRIBUTOR_DIM_PARTY_NATURAL_KEY_HASH_UUID
	FROM 
		( 
		SELECT 
			CLEAN_STRING(SRC.CARR_ADMN_SYS_CD) 				   	AS CARR_ADMN_SYS_CD,
			CLEAN_STRING('IPA')  AS IPA,
			CLEAN_STRING(SRC.HLDG_KEY_PFX)						AS HLDG_KEY_PFX,
			CASE WHEN CLEAN_STRING(SRC.CARR_ADMN_SYS_CD) = 'Hap' THEN (CLEAN_STRING(LPAD(SRC.HLDG_KEY,20,'0'))) -----added condition over the including alpha numeric 
			ELSE CLEAN_STRING(SRC.HLDG_KEY)END 				AS HLDG_KEY,
--			CLEAN_STRING(SRC.HLDG_KEY),							AS HLDG_KEY,
			CLEAN_STRING(SRC.HLDG_KEY_SFX)						AS HLDG_KEY_SFX,
			COALESCE(T1.DIM_PARTY_NATURAL_KEY_HASH_UUID,UUID_GEN(NULL)::UUID) AS DIM_PARTY_NATURAL_KEY_HASH_UUID,
			UUID_GEN(CLEAN_STRING(SRC.HLDG_ROLE_CD))::UUID 		AS REF_PARTY_ROLE_NATURAL_KEY_HASH_UUID, 
			UUID_GEN(CLEAN_STRING(SRC.HLDG_ROLE_STYP_CD))::UUID AS REF_PARTY_SUB_ROLE_NATURAL_KEY_HASH_UUID, 
			UUID_GEN(NULL)::UUID 								AS DIM_ACCOUNT_NATURAL_KEY_HASH_UUID, 
			SRC.REL_START_DATE::DATE						 	AS BEGIN_DT,
			SRC.REL_START_DATE::TIMESTAMP(6) 					AS BEGIN_DTM,
			 ROW_PROCESS_DTM::timestamp(6)						AS ROW_PROCESS_DTM,
			--:audit_id AS AUDIT_ID,
			FALSE 												AS LOGICAL_DELETE_IND, 
			CASE WHEN src.rel_end_date::DATE <> '12-31-9999' 
			THEN FALSE ELSE TRUE END 							AS CURRENT_ROW_IND,
			SRC.REL_END_DATE::DATE 								AS END_DT,  
			SRC.REL_END_DATE::TIMESTAMP(6) 						AS END_DTM, 
			'47' 												AS SOURCE_SYSTEM_ID, 
			FALSE 												AS RESTRICTED_ROW_IND, 
			--:audit_id as UPDATE_AUDIT_ID, 
			UUID_GEN(NULL)::UUID 								AS DIM_ADDRESS_NATURAL_KEY_HASH_UUID, 
			NULL 												AS ADDRESS_TYPE_CDE, 
			NULL 												AS ATTENTION_LINE_TXT, 
			UUID_GEN((NULL))::UUID                              AS DIM_PHONE_NATURAL_KEY_HASH_UUID,
			UUID_GEN((NULL))::UUID                              AS DIM_ELECTRONIC_ADDRESS_NATURAL_KEY_HASH_UUID,
			UUID_GEN((NULL))::UUID                              AS DIM_PARTY_AKA_NAME_NATURAL_KEY_HASH_UUID,
			UUID_GEN((NULL))::UUID                              AS	ADVISOR_DIM_SELLING_AGREEMENT_NATURAL_KEY_HASH_UUID,
			UUID_GEN((NULL))::UUID                              AS FIRM_DIM_SELLING_AGREEMENT_NATURAL_KEY_HASH_UUID,
			--UUID_GEN((NULL))::UUID                              AS AGENCY_DIM_PARTY_NATURAL_KEY_HASH_UUID,
			NULL 												AS SOURCE_PARTY_ROLE_CDE, 
			NULL 												AS SOURCE_PARTY_SUB_ROLE_CDE, 
			NULL 												AS SOURCE_ADDRESS_TYPE_CDE, 
			FALSE                                               AS SOURCE_DELETE_IND, 
			NULL 												AS BENEFICIARY_ISS_PER_STIRPES_CDE, 
			REL_START_DATE::DATE 								AS BUSINESS_STRT_DT, 
			REL_END_DATE::DATE 									AS BUSINESS_END_DT,
			COALESCE(T1.DIM_PARTY_NATURAL_KEY_HASH_UUID,UUID_GEN(NULL)::UUID) AS AGENCY_DIM_PARTY_NATURAL_KEY_HASH_UUID,
			COALESCE(T1.DIM_PARTY_NATURAL_KEY_HASH_UUID,UUID_GEN(NULL)::UUID) AS DISTRIBUTOR_DIM_PARTY_NATURAL_KEY_HASH_UUID
			FROM edw_staging.pdcr_rel_edw_td_svcagy_snapshot src 
			LEFT JOIN 
				(    
				SELECT DIM_PARTY_NATURAL_KEY_HASH_UUID,sor_party_id FROM EDW_vw.party_master_of_masters_xref_vw xref-------------------------CHANGE BEFRE PROD
				WHERE upper(xref.party_id_type_cde) = 'AGENCY' AND xref.current_row_ind AND xref.logical_delete_ind = False
				) T1
				ON coalesce(btrim(T1.sor_party_id),'') = coalesce(btrim(src.src_id),'')----------------------AGENCY_DIM_PARTY_NATURAL_KEY_HASH_UUID
			--WHERE CLEAN_STRING(CARR_ADMN_SYS_CD)<> 'Combnd' AND SOURCE_SYSTEM_ID= '47'  AND REGEXP_NOT_LIKE(HLDG_KEY,'-')----to aviod future income of the combnd 
			--TERSUN-3418
			where COALESCE(SRC.HUB_STATE_IND,1) >= 0   
		) Q1
	) Q2 ;
	

INSERT INTO TEMP_PDCR_REL_REL_PARTY_AGREEMENT( 
	carr_admn_sys_cd,
	DIM_AGREEMENT_NATURAL_KEY_HASH_UUID, 
	DIM_PARTY_NATURAL_KEY_HASH_UUID, 
	REF_PARTY_ROLE_NATURAL_KEY_HASH_UUID, 
	REF_PARTY_SUB_ROLE_NATURAL_KEY_HASH_UUID, 
	DIM_ACCOUNT_NATURAL_KEY_HASH_UUID, 
	BEGIN_DT, 
	BEGIN_DTM, 
	ROW_PROCESS_DTM, 
	--AUDIT_ID, 
	LOGICAL_DELETE_IND, 
	CHECK_SUM, 
	CURRENT_ROW_IND, 
	END_DT, 
	END_DTM, 
	SOURCE_SYSTEM_ID, 
	RESTRICTED_ROW_IND, 
	--UPDATE_AUDIT_ID, 
	DIM_ADDRESS_NATURAL_KEY_HASH_UUID, 
	ADDRESS_TYPE_CDE, 
	ATTENTION_LINE_TXT, 
	DIM_PHONE_NATURAL_KEY_HASH_UUID, 
	DIM_ELECTRONIC_ADDRESS_NATURAL_KEY_HASH_UUID, 
	DIM_PARTY_AKA_NAME_NATURAL_KEY_HASH_UUID, 
	ADVISOR_DIM_SELLING_AGREEMENT_NATURAL_KEY_HASH_UUID,
	FIRM_DIM_SELLING_AGREEMENT_NATURAL_KEY_HASH_UUID,
	AGENCY_DIM_PARTY_NATURAL_KEY_HASH_UUID,
	SOURCE_PARTY_ROLE_CDE, 
	SOURCE_PARTY_SUB_ROLE_CDE, 
	SOURCE_ADDRESS_TYPE_CDE, 
	SOURCE_DELETE_IND, 
	BENEFICIARY_ISS_PER_STIRPES_CDE, 
	BUSINESS_STRT_DT, 
	BUSINESS_END_DT,
	DISTRIBUTOR_DIM_PARTY_NATURAL_KEY_HASH_UUID
	)
	SELECT
	carr_admn_sys_cd,
	DIM_AGREEMENT_NATURAL_KEY_HASH_UUID, 
	DIM_PARTY_NATURAL_KEY_HASH_UUID, 
	REF_PARTY_ROLE_NATURAL_KEY_HASH_UUID, 
	REF_PARTY_SUB_ROLE_NATURAL_KEY_HASH_UUID, 
	DIM_ACCOUNT_NATURAL_KEY_HASH_UUID, 
	BEGIN_DT, 
	BEGIN_DTM, 
	ROW_PROCESS_DTM, 
	--AUDIT_ID, 
	LOGICAL_DELETE_IND, 
	CHECK_SUM, 
	CURRENT_ROW_IND, 
	END_DT, 
	END_DTM, 
	SOURCE_SYSTEM_ID, 
	RESTRICTED_ROW_IND, 
	--UPDATE_AUDIT_ID, 
	DIM_ADDRESS_NATURAL_KEY_HASH_UUID, 
	ADDRESS_TYPE_CDE, 
	ATTENTION_LINE_TXT, 
	DIM_PHONE_NATURAL_KEY_HASH_UUID, 
	DIM_ELECTRONIC_ADDRESS_NATURAL_KEY_HASH_UUID, 
	DIM_PARTY_AKA_NAME_NATURAL_KEY_HASH_UUID, 
	ADVISOR_DIM_SELLING_AGREEMENT_NATURAL_KEY_HASH_UUID,
	FIRM_DIM_SELLING_AGREEMENT_NATURAL_KEY_HASH_UUID,
	AGENCY_DIM_PARTY_NATURAL_KEY_HASH_UUID,
	SOURCE_PARTY_ROLE_CDE, 
	SOURCE_PARTY_SUB_ROLE_CDE, 
	SOURCE_ADDRESS_TYPE_CDE, 
	SOURCE_DELETE_IND, 
	BENEFICIARY_ISS_PER_STIRPES_CDE, 
	BUSINESS_STRT_DT, 
	BUSINESS_END_DT,
	DISTRIBUTOR_DIM_PARTY_NATURAL_KEY_HASH_UUID
	FROM(
	SELECT
		carr_admn_sys_cd,
		CASE WHEN (CLEAN_STRING(CARR_ADMN_SYS_CD),
		IPA,
		CLEAN_STRING(HLDG_KEY_PFX),
		CLEAN_STRING(HLDG_KEY),
		CLEAN_STRING(HLDG_KEY_SFX)) IS NOT NULL THEN 
		UUID_GEN(CLEAN_STRING(CARR_ADMN_SYS_CD),
		IPA,
		CLEAN_STRING(HLDG_KEY_PFX),
		CLEAN_STRING(HLDG_KEY),
		CLEAN_STRING(HLDG_KEY_SFX))::UUID ELSE 
		UUID_GEN(NULL)::UUID END					AS DIM_AGREEMENT_NATURAL_KEY_HASH_UUID,  
		DIM_PARTY_NATURAL_KEY_HASH_UUID, 
		REF_PARTY_ROLE_NATURAL_KEY_HASH_UUID, 
		REF_PARTY_SUB_ROLE_NATURAL_KEY_HASH_UUID, 
		DIM_ACCOUNT_NATURAL_KEY_HASH_UUID, 
		BEGIN_DT, 
		BEGIN_DTM, 
		ROW_PROCESS_DTM, 
		--AUDIT_ID, 
		LOGICAL_DELETE_IND, 
		UUID_GEN(SOURCE_DELETE_IND,SOURCE_PARTY_ROLE_CDE,SOURCE_PARTY_SUB_ROLE_CDE)::UUID AS CHECK_SUM,
		CURRENT_ROW_IND, 
		END_DT, 
		END_DTM, 
		SOURCE_SYSTEM_ID, 
		RESTRICTED_ROW_IND, 
		--UPDATE_AUDIT_ID, 
		DIM_ADDRESS_NATURAL_KEY_HASH_UUID, 
		ADDRESS_TYPE_CDE, 
		ATTENTION_LINE_TXT, 
		DIM_PHONE_NATURAL_KEY_HASH_UUID, 
		DIM_ELECTRONIC_ADDRESS_NATURAL_KEY_HASH_UUID, 
		DIM_PARTY_AKA_NAME_NATURAL_KEY_HASH_UUID, 
		ADVISOR_DIM_SELLING_AGREEMENT_NATURAL_KEY_HASH_UUID,
		FIRM_DIM_SELLING_AGREEMENT_NATURAL_KEY_HASH_UUID,
		AGENCY_DIM_PARTY_NATURAL_KEY_HASH_UUID,
		SOURCE_PARTY_ROLE_CDE, 
		SOURCE_PARTY_SUB_ROLE_CDE, 
		SOURCE_ADDRESS_TYPE_CDE, 
		SOURCE_DELETE_IND, 
		BENEFICIARY_ISS_PER_STIRPES_CDE, 
		BUSINESS_STRT_DT, 
		BUSINESS_END_DT,
		DISTRIBUTOR_DIM_PARTY_NATURAL_KEY_HASH_UUID
	FROM(
	SELECT 
			CLEAN_STRING(SRC.CARR_ADMN_SYS_CD) 				   	AS CARR_ADMN_SYS_CD,
			CLEAN_STRING('IPA') AS IPA,
			CLEAN_STRING(SRC.HLDG_KEY_PFX)						AS HLDG_KEY_PFX,
			CASE WHEN CLEAN_STRING(SRC.CARR_ADMN_SYS_CD) = 'Hap' THEN (CLEAN_STRING(LPAD(SRC.HLDG_KEY,20,'0'))) -----added condition over the including alpha numeric 
			ELSE CLEAN_STRING(SRC.HLDG_KEY)END 				AS HLDG_KEY,
--			CLEAN_STRING(SRC.HLDG_KEY),							AS HLDG_KEY,
			CLEAN_STRING(SRC.HLDG_KEY_SFX)						AS HLDG_KEY_SFX,
			COALESCE(T1.DIM_PARTY_NATURAL_KEY_HASH_UUID,UUID_GEN(NULL)::UUID) AS DIM_PARTY_NATURAL_KEY_HASH_UUID,
			UUID_GEN(CLEAN_STRING(SRC.HLDG_ROLE_CD))::UUID 		AS REF_PARTY_ROLE_NATURAL_KEY_HASH_UUID, 
			UUID_GEN(CLEAN_STRING(SRC.HLDG_ROLE_STYP_CD))::UUID AS REF_PARTY_SUB_ROLE_NATURAL_KEY_HASH_UUID, 
			UUID_GEN(NULL)::UUID 								AS DIM_ACCOUNT_NATURAL_KEY_HASH_UUID, 
			SRC.REL_START_DATE::DATE						 	AS BEGIN_DT,
			SRC.REL_START_DATE::TIMESTAMP(6) 					AS BEGIN_DTM,
			CURRENT_TIMESTAMP 									AS ROW_PROCESS_DTM,
			--:audit_id AS AUDIT_ID,
			FALSE 												AS LOGICAL_DELETE_IND, 
			FALSE 												AS CURRENT_ROW_IND,
			CURRENT_DATE 								        AS END_DT,  
			CURRENT_TIMESTAMP(6) 						        AS END_DTM, 
			'47' 												AS SOURCE_SYSTEM_ID, 
			FALSE 												AS RESTRICTED_ROW_IND, 
			--:audit_id as UPDATE_AUDIT_ID, 
			UUID_GEN(NULL)::UUID 								AS DIM_ADDRESS_NATURAL_KEY_HASH_UUID, 
			NULL 												AS ADDRESS_TYPE_CDE, 
			NULL 												AS ATTENTION_LINE_TXT, 
			UUID_GEN((NULL))::UUID                              AS DIM_PHONE_NATURAL_KEY_HASH_UUID,
			UUID_GEN((NULL))::UUID                              AS DIM_ELECTRONIC_ADDRESS_NATURAL_KEY_HASH_UUID,
			UUID_GEN((NULL))::UUID                              AS DIM_PARTY_AKA_NAME_NATURAL_KEY_HASH_UUID,
			UUID_GEN((NULL))::UUID                              AS	ADVISOR_DIM_SELLING_AGREEMENT_NATURAL_KEY_HASH_UUID,
			UUID_GEN((NULL))::UUID                              AS FIRM_DIM_SELLING_AGREEMENT_NATURAL_KEY_HASH_UUID,
			--UUID_GEN((NULL))::UUID                              AS AGENCY_DIM_PARTY_NATURAL_KEY_HASH_UUID,
			NULL 												AS SOURCE_PARTY_ROLE_CDE, 
			NULL 												AS SOURCE_PARTY_SUB_ROLE_CDE, 
			NULL 												AS SOURCE_ADDRESS_TYPE_CDE, 
			TRUE                                                AS SOURCE_DELETE_IND, 
			NULL 												AS BENEFICIARY_ISS_PER_STIRPES_CDE, 
			REL_START_DATE::DATE 								AS BUSINESS_STRT_DT, 
			REL_END_DATE::DATE 									AS BUSINESS_END_DT,
			COALESCE(T1.DIM_PARTY_NATURAL_KEY_HASH_UUID,UUID_GEN(NULL)::UUID) AS AGENCY_DIM_PARTY_NATURAL_KEY_HASH_UUID,
			COALESCE(T1.DIM_PARTY_NATURAL_KEY_HASH_UUID,UUID_GEN(NULL)::UUID) AS DISTRIBUTOR_DIM_PARTY_NATURAL_KEY_HASH_UUID
			FROM edw_staging.pdcr_rel_edw_td_svcagy_snapshot src 
			LEFT JOIN 
				(    
				SELECT DIM_PARTY_NATURAL_KEY_HASH_UUID,sor_party_id FROM EDW_vw.party_master_of_masters_xref_vw xref-------------------------CHANGE BEFRE PROD
				WHERE upper(xref.party_id_type_cde) = 'AGENCY' AND xref.current_row_ind AND xref.logical_delete_ind = False
				) T1
				ON coalesce(btrim(T1.sor_party_id),'') = coalesce(btrim(src.src_id),'')----------------------AGENCY_DIM_PARTY_NATURAL_KEY_HASH_UUID
			--WHERE CLEAN_STRING(CARR_ADMN_SYS_CD)<> 'Combnd' AND SOURCE_SYSTEM_ID= '47'  AND REGEXP_NOT_LIKE(HLDG_KEY,'-')----to aviod future income of the combnd 
			where COALESCE(SRC.HUB_STATE_IND,1) < 0  
		)Q_1
	)Q_2;



COMMIT;
---------***********2. Loading staging data from PDCR_REL_EDW_TD_PDCR_AGRL & PDCR_REL_EDW_TD_PDCR_AGRL where UPPER(CARR_ADMN_SYS_CD) <> 'COMBND' ***********----------
INSERT INTO TEMP_PDCR_REL_REL_PARTY_AGREEMENT 
(
	CARR_ADMN_SYS_CD,
	DIM_AGREEMENT_NATURAL_KEY_HASH_UUID, 
	DIM_PARTY_NATURAL_KEY_HASH_UUID, 
	REF_PARTY_ROLE_NATURAL_KEY_HASH_UUID, 
	REF_PARTY_SUB_ROLE_NATURAL_KEY_HASH_UUID, 
	DIM_ACCOUNT_NATURAL_KEY_HASH_UUID, 
	BEGIN_DT, 
	BEGIN_DTM, 
	ROW_PROCESS_DTM, 
	--AUDIT_ID, 
	LOGICAL_DELETE_IND, 
	CHECK_SUM, 
	CURRENT_ROW_IND, 
	END_DT, 
	END_DTM, 
	SOURCE_SYSTEM_ID, 
	RESTRICTED_ROW_IND, 
	--UPDATE_AUDIT_ID, 
	DIM_ADDRESS_NATURAL_KEY_HASH_UUID, 
	ADDRESS_TYPE_CDE, 
	ATTENTION_LINE_TXT, 
	DIM_PHONE_NATURAL_KEY_HASH_UUID, 
	DIM_ELECTRONIC_ADDRESS_NATURAL_KEY_HASH_UUID, 
	DIM_PARTY_AKA_NAME_NATURAL_KEY_HASH_UUID,
	ADVISOR_DIM_SELLING_AGREEMENT_NATURAL_KEY_HASH_UUID,
	FIRM_DIM_SELLING_AGREEMENT_NATURAL_KEY_HASH_UUID,	
	AGENCY_DIM_PARTY_NATURAL_KEY_HASH_UUID,
	DISTRIBUTOR_DIM_PARTY_NATURAL_KEY_HASH_UUID,
	SOURCE_PARTY_ROLE_CDE, 
	SOURCE_PARTY_SUB_ROLE_CDE, 
	SOURCE_ADDRESS_TYPE_CDE, 
	SOURCE_DELETE_IND, 
	beneficiary_ISS_per_stirpes_cde, 
	business_strt_dt, 
	business_end_dt
)	
	SELECT 
	CARR_ADMN_SYS_CD,
	DIM_AGREEMENT_NATURAL_KEY_HASH_UUID, 
	DIM_PARTY_NATURAL_KEY_HASH_UUID, 
	REF_PARTY_ROLE_NATURAL_KEY_HASH_UUID, 
	REF_PARTY_SUB_ROLE_NATURAL_KEY_HASH_UUID, 
	DIM_ACCOUNT_NATURAL_KEY_HASH_UUID, 
	BEGIN_DT, 
	BEGIN_DTM, 
	ROW_PROCESS_DTM, 
	--AUDIT_ID, 
	LOGICAL_DELETE_IND, 
	CHECK_SUM, 
	CURRENT_ROW_IND, 
	END_DT, 
	END_DTM, 
	SOURCE_SYSTEM_ID, 
	RESTRICTED_ROW_IND, 
	--UPDATE_AUDIT_ID, 
	DIM_ADDRESS_NATURAL_KEY_HASH_UUID, 
	ADDRESS_TYPE_CDE, 
	ATTENTION_LINE_TXT, 
	DIM_PHONE_NATURAL_KEY_HASH_UUID, 
	DIM_ELECTRONIC_ADDRESS_NATURAL_KEY_HASH_UUID, 
	DIM_PARTY_AKA_NAME_NATURAL_KEY_HASH_UUID,
	ADVISOR_DIM_SELLING_AGREEMENT_NATURAL_KEY_HASH_UUID,
	FIRM_DIM_SELLING_AGREEMENT_NATURAL_KEY_HASH_UUID,	
	AGENCY_DIM_PARTY_NATURAL_KEY_HASH_UUID,
	DISTRIBUTOR_DIM_PARTY_NATURAL_KEY_HASH_UUID,
	SOURCE_PARTY_ROLE_CDE, 
	SOURCE_PARTY_SUB_ROLE_CDE, 
	SOURCE_ADDRESS_TYPE_CDE, 
	SOURCE_DELETE_IND, 
	beneficiary_ISS_per_stirpes_cde, 
	business_strt_dt, 
	business_end_dt
	--operator_ind 
FROM (
		SELECT 
		CARR_ADMN_SYS_CD,
		CASE WHEN (CLEAN_STRING(CARR_ADMN_SYS_CD),
		IPA,
		CLEAN_STRING(HLDG_KEY_PFX),
		CLEAN_STRING(HLDG_KEY),
		CLEAN_STRING(HLDG_KEY_SFX)) IS NOT NULL THEN 
		UUID_GEN(CLEAN_STRING(CARR_ADMN_SYS_CD),
		IPA,
		CLEAN_STRING(HLDG_KEY_PFX),
		CLEAN_STRING(HLDG_KEY),
		CLEAN_STRING(HLDG_KEY_SFX))::UUID  ELSE 
		UUID_GEN(NULL)::UUID END 						    AS DIM_AGREEMENT_NATURAL_KEY_HASH_UUID,
		DIM_PARTY_NATURAL_KEY_HASH_UUID, 
		REF_PARTY_ROLE_NATURAL_KEY_HASH_UUID, 
		REF_PARTY_SUB_ROLE_NATURAL_KEY_HASH_UUID, 
		DIM_ACCOUNT_NATURAL_KEY_HASH_UUID, 
		BEGIN_DT, 
		BEGIN_DTM, 
		ROW_PROCESS_DTM, 
		--AUDIT_ID, 
		LOGICAL_DELETE_IND, 
		UUID_GEN(SOURCE_DELETE_IND,SOURCE_PARTY_ROLE_CDE,SOURCE_PARTY_SUB_ROLE_CDE)::UUID AS CHECK_SUM,
		CURRENT_ROW_IND, 
		END_DT, 
		END_DTM, 
		SOURCE_SYSTEM_ID, 
		RESTRICTED_ROW_IND, 
		--UPDATE_AUDIT_ID, 
		DIM_ADDRESS_NATURAL_KEY_HASH_UUID, 
		ADDRESS_TYPE_CDE, 
		ATTENTION_LINE_TXT, 
		DIM_PHONE_NATURAL_KEY_HASH_UUID, 
		DIM_ELECTRONIC_ADDRESS_NATURAL_KEY_HASH_UUID, 
		DIM_PARTY_AKA_NAME_NATURAL_KEY_HASH_UUID, 
		ADVISOR_DIM_SELLING_AGREEMENT_NATURAL_KEY_HASH_UUID,
		FIRM_DIM_SELLING_AGREEMENT_NATURAL_KEY_HASH_UUID,
		AGENCY_DIM_PARTY_NATURAL_KEY_HASH_UUID,
		DISTRIBUTOR_DIM_PARTY_NATURAL_KEY_HASH_UUID,
		SOURCE_PARTY_ROLE_CDE, 
		SOURCE_PARTY_SUB_ROLE_CDE, 
		SOURCE_ADDRESS_TYPE_CDE, 
		SOURCE_DELETE_IND, 
		BENEFICIARY_ISS_PER_STIRPES_CDE, 
		BUSINESS_STRT_DT, 
		BUSINESS_END_DT
	FROM 
		( 
			SELECT 
			CLEAN_STRING(PD.CARR_ADMN_SYS_CD)						AS CARR_ADMN_SYS_CD,
			 CLEAN_STRING('IPA')  AS IPA,
			CLEAN_STRING(PD.HLDG_KEY_PFX)							AS HLDG_KEY_PFX,
			case when clean_string(CARR_ADMN_SYS_CD)= 'Hap' THEN (CLEAN_STRING(lpad(pd.HLDG_KEY,20,'0')))
     		ELSE CLEAN_STRING(PD.HLDG_KEY) END 						AS HLDG_KEY,
     		--CLEAN_STRING(RIGHT('00000000000000000000'||Btrim(regexp_replace(PD.HLDG_KEY, '[a-zA-Z]', '')),20)),
			CLEAN_STRING(PD.HLDG_KEY_SFX)							AS HLDG_KEY_SFX,
			UUID_GEN(BTRIM(VoltageAccess(T1.member_id,'sorparty')))::UUID 				    AS DIM_PARTY_NATURAL_KEY_HASH_UUID, 
			UUID_GEN(CLEAN_STRING(PD.HLDG_ROLE_CD))::UUID 			AS REF_PARTY_ROLE_NATURAL_KEY_HASH_UUID, 
			UUID_GEN(CLEAN_STRING(PD.HLDG_ROLE_STYP_CD))::UUID 		AS REF_PARTY_SUB_ROLE_NATURAL_KEY_HASH_UUID, 
			UUID_GEN(NULL)::UUID 									AS DIM_ACCOUNT_NATURAL_KEY_HASH_UUID, 
			PD.REL_START_DATE::DATE									AS BEGIN_DT,
			PD.REL_START_DATE::TIMESTAMP(6) 						AS BEGIN_DTM,
			CURRENT_TIMESTAMP 										AS ROW_PROCESS_DTM,
			--:audit_id AS AUDIT_ID,
			FALSE 													AS LOGICAL_DELETE_IND,
			CASE WHEN PD.rel_end_date::DATE <> '12-31-9999' 
			THEN FALSE ELSE TRUE END 								AS CURRENT_ROW_IND,
			PD.REL_END_DATE::DATE 									AS END_DT,
			PD.REL_END_DATE::TIMESTAMP(6) 							AS END_DTM,
			'47' 													AS SOURCE_SYSTEM_ID, 
			FALSE 													AS RESTRICTED_ROW_IND, 
			--:audit_id as UPDATE_AUDIT_ID, 
			UUID_GEN(NULL)::UUID 									AS DIM_ADDRESS_NATURAL_KEY_HASH_UUID, 
			NULL 													AS ADDRESS_TYPE_CDE, 
			NULL 													AS ATTENTION_LINE_TXT, 
			UUID_GEN((NULL))::UUID                               	AS DIM_PHONE_NATURAL_KEY_HASH_UUID,
			UUID_GEN((NULL))::UUID                        		 	AS DIM_ELECTRONIC_ADDRESS_NATURAL_KEY_HASH_UUID,
			UUID_GEN((NULL))::UUID                               	AS DIM_PARTY_AKA_NAME_NATURAL_KEY_HASH_UUID,
			UUID_GEN((NULL))::UUID                               	AS ADVISOR_DIM_SELLING_AGREEMENT_NATURAL_KEY_HASH_UUID,
			UUID_GEN((NULL))::UUID                               	AS FIRM_DIM_SELLING_AGREEMENT_NATURAL_KEY_HASH_UUID,
			UUID_GEN((NULL))::UUID									AS AGENCY_DIM_PARTY_NATURAL_KEY_HASH_UUID,
			UUID_GEN((NULL))::UUID									AS DISTRIBUTOR_DIM_PARTY_NATURAL_KEY_HASH_UUID,
			NULL 												 	AS SOURCE_PARTY_ROLE_CDE, 
			NULL 													AS SOURCE_PARTY_SUB_ROLE_CDE, 
			NULL 													AS SOURCE_ADDRESS_TYPE_CDE, 
			FALSE                                                   AS SOURCE_DELETE_IND, 
			NULL 													AS BENEFICIARY_ISS_PER_STIRPES_CDE, 
			REL_START_DATE::DATE 									AS BUSINESS_STRT_DT, 
			REL_END_DATE::DATE 										AS BUSINESS_END_DT 
			from edw_staging.pdcr_rel_edw_td_pdcr_agrl_snapshot PD 
				LEFT JOIN 
				(    
				SELECT MEMBER_ID,SRC_SYS_ID FROM edw_staging.amdm_advsr_member_id_xref_out_snapshot 
				WHERE SRC_SYS = 'FSBP' AND add_upd_del_ind <> 'D'
				) T1
				on coalesce(btrim(T1.src_sys_id),'') = coalesce(btrim(PD.SRC_ID),'')
			--WHERE CLEAN_STRING(CARR_ADMN_SYS_CD)<> 'Combnd' AND SOURCE_SYSTEM_ID= '47'  AND REGEXP_NOT_LIKE(HLDG_KEY,'-')
			--TERSUN-3418
			where COALESCE(PD.HUB_STATE_IND,1) >= 0  
		)Q1
	)Q2;	
	
COMMIT;

--SELECT COUNT(*) FROM TEMP_PDCR_REL_REL_PARTY_AGREEMENT WHERE CURRENT_ROW_IND--9956375

INSERT INTO TEMP_PDCR_REL_REL_PARTY_AGREEMENT 
(
	CARR_ADMN_SYS_CD,
	DIM_AGREEMENT_NATURAL_KEY_HASH_UUID, 
	DIM_PARTY_NATURAL_KEY_HASH_UUID, 
	REF_PARTY_ROLE_NATURAL_KEY_HASH_UUID, 
	REF_PARTY_SUB_ROLE_NATURAL_KEY_HASH_UUID, 
	DIM_ACCOUNT_NATURAL_KEY_HASH_UUID, 
	BEGIN_DT, 
	BEGIN_DTM, 
	ROW_PROCESS_DTM, 
	--AUDIT_ID, 
	LOGICAL_DELETE_IND, 
	CHECK_SUM, 
	CURRENT_ROW_IND, 
	END_DT, 
	END_DTM, 
	SOURCE_SYSTEM_ID, 
	RESTRICTED_ROW_IND, 
	--UPDATE_AUDIT_ID, 
	DIM_ADDRESS_NATURAL_KEY_HASH_UUID, 
	ADDRESS_TYPE_CDE, 
	ATTENTION_LINE_TXT, 
	DIM_PHONE_NATURAL_KEY_HASH_UUID, 
	DIM_ELECTRONIC_ADDRESS_NATURAL_KEY_HASH_UUID, 
	DIM_PARTY_AKA_NAME_NATURAL_KEY_HASH_UUID,
	ADVISOR_DIM_SELLING_AGREEMENT_NATURAL_KEY_HASH_UUID,
	FIRM_DIM_SELLING_AGREEMENT_NATURAL_KEY_HASH_UUID,	
	AGENCY_DIM_PARTY_NATURAL_KEY_HASH_UUID,
	DISTRIBUTOR_DIM_PARTY_NATURAL_KEY_HASH_UUID,
	SOURCE_PARTY_ROLE_CDE, 
	SOURCE_PARTY_SUB_ROLE_CDE, 
	SOURCE_ADDRESS_TYPE_CDE, 
	SOURCE_DELETE_IND, 
	beneficiary_ISS_per_stirpes_cde, 
	business_strt_dt, 
	business_end_dt
	)	
	SELECT CARR_ADMN_SYS_CD,
	DIM_AGREEMENT_NATURAL_KEY_HASH_UUID, 
	DIM_PARTY_NATURAL_KEY_HASH_UUID, 
	REF_PARTY_ROLE_NATURAL_KEY_HASH_UUID, 
	REF_PARTY_SUB_ROLE_NATURAL_KEY_HASH_UUID, 
	DIM_ACCOUNT_NATURAL_KEY_HASH_UUID, 
	BEGIN_DT, 
	BEGIN_DTM, 
	ROW_PROCESS_DTM, 
	--AUDIT_ID, 
	LOGICAL_DELETE_IND, 
	CHECK_SUM, 
	CURRENT_ROW_IND, 
	END_DT, 
	END_DTM, 
	SOURCE_SYSTEM_ID, 
	RESTRICTED_ROW_IND, 
	--UPDATE_AUDIT_ID, 
	DIM_ADDRESS_NATURAL_KEY_HASH_UUID, 
	ADDRESS_TYPE_CDE, 
	ATTENTION_LINE_TXT, 
	DIM_PHONE_NATURAL_KEY_HASH_UUID, 
	DIM_ELECTRONIC_ADDRESS_NATURAL_KEY_HASH_UUID, 
	DIM_PARTY_AKA_NAME_NATURAL_KEY_HASH_UUID,
	ADVISOR_DIM_SELLING_AGREEMENT_NATURAL_KEY_HASH_UUID,
	FIRM_DIM_SELLING_AGREEMENT_NATURAL_KEY_HASH_UUID,	
	AGENCY_DIM_PARTY_NATURAL_KEY_HASH_UUID,
	DISTRIBUTOR_DIM_PARTY_NATURAL_KEY_HASH_UUID,
	SOURCE_PARTY_ROLE_CDE, 
	SOURCE_PARTY_SUB_ROLE_CDE, 
	SOURCE_ADDRESS_TYPE_CDE, 
	SOURCE_DELETE_IND, 
	beneficiary_ISS_per_stirpes_cde, 
	business_strt_dt, 
	business_end_dt
	--operator_ind 
FROM (
		SELECT 
		CARR_ADMN_SYS_CD,
		CASE WHEN (CLEAN_STRING(CARR_ADMN_SYS_CD),
		IPA,
		CLEAN_STRING(HLDG_KEY_PFX),
		CLEAN_STRING(HLDG_KEY),
		CLEAN_STRING(HLDG_KEY_SFX)) IS NOT NULL THEN 
		UUID_GEN(CLEAN_STRING(CARR_ADMN_SYS_CD),
		IPA,
		CLEAN_STRING(HLDG_KEY_PFX),
		CLEAN_STRING(HLDG_KEY),
		CLEAN_STRING(HLDG_KEY_SFX))::UUID  ELSE 
		UUID_GEN(NULL)::UUID END 						    AS DIM_AGREEMENT_NATURAL_KEY_HASH_UUID,
		DIM_PARTY_NATURAL_KEY_HASH_UUID, 
		REF_PARTY_ROLE_NATURAL_KEY_HASH_UUID, 
		REF_PARTY_SUB_ROLE_NATURAL_KEY_HASH_UUID, 
		DIM_ACCOUNT_NATURAL_KEY_HASH_UUID, 
		BEGIN_DT, 
		BEGIN_DTM, 
		ROW_PROCESS_DTM, 
		--AUDIT_ID, 
		LOGICAL_DELETE_IND, 
		UUID_GEN(SOURCE_DELETE_IND,SOURCE_PARTY_ROLE_CDE,SOURCE_PARTY_SUB_ROLE_CDE)::UUID AS CHECK_SUM,
		CURRENT_ROW_IND, 
		END_DT, 
		END_DTM, 
		SOURCE_SYSTEM_ID, 
		RESTRICTED_ROW_IND, 
		--UPDATE_AUDIT_ID, 
		DIM_ADDRESS_NATURAL_KEY_HASH_UUID, 
		ADDRESS_TYPE_CDE, 
		ATTENTION_LINE_TXT, 
		DIM_PHONE_NATURAL_KEY_HASH_UUID, 
		DIM_ELECTRONIC_ADDRESS_NATURAL_KEY_HASH_UUID, 
		DIM_PARTY_AKA_NAME_NATURAL_KEY_HASH_UUID, 
		ADVISOR_DIM_SELLING_AGREEMENT_NATURAL_KEY_HASH_UUID,
		FIRM_DIM_SELLING_AGREEMENT_NATURAL_KEY_HASH_UUID,
		AGENCY_DIM_PARTY_NATURAL_KEY_HASH_UUID,
		DISTRIBUTOR_DIM_PARTY_NATURAL_KEY_HASH_UUID,
		SOURCE_PARTY_ROLE_CDE, 
		SOURCE_PARTY_SUB_ROLE_CDE, 
		SOURCE_ADDRESS_TYPE_CDE, 
		SOURCE_DELETE_IND, 
		BENEFICIARY_ISS_PER_STIRPES_CDE, 
		BUSINESS_STRT_DT, 
		BUSINESS_END_DT
	FROM 
	(
		SELECT 
			CLEAN_STRING(PD.CARR_ADMN_SYS_CD)						AS CARR_ADMN_SYS_CD,
			CLEAN_STRING('IPA')  AS IPA,
			CLEAN_STRING(PD.HLDG_KEY_PFX)							AS HLDG_KEY_PFX,
			case when clean_string(CARR_ADMN_SYS_CD)= 'Hap' THEN (CLEAN_STRING(lpad(pd.HLDG_KEY,20,'0')))
     		ELSE CLEAN_STRING(PD.HLDG_KEY) END 						AS HLDG_KEY,
     		--CLEAN_STRING(RIGHT('00000000000000000000'||Btrim(regexp_replace(PD.HLDG_KEY, '[a-zA-Z]', '')),20)),
			CLEAN_STRING(PD.HLDG_KEY_SFX)							AS HLDG_KEY_SFX,
			UUID_GEN(BTRIM(VoltageAccess(T1.member_id,'sorparty')))::UUID 				    AS DIM_PARTY_NATURAL_KEY_HASH_UUID, 
			UUID_GEN(CLEAN_STRING(PD.HLDG_ROLE_CD))::UUID 			AS REF_PARTY_ROLE_NATURAL_KEY_HASH_UUID, 
			UUID_GEN(CLEAN_STRING(PD.HLDG_ROLE_STYP_CD))::UUID 		AS REF_PARTY_SUB_ROLE_NATURAL_KEY_HASH_UUID, 
			UUID_GEN(NULL)::UUID 									AS DIM_ACCOUNT_NATURAL_KEY_HASH_UUID, 
			PD.REL_START_DATE::DATE									AS BEGIN_DT,
			PD.REL_START_DATE::TIMESTAMP(6) 						AS BEGIN_DTM,
			CURRENT_TIMESTAMP 										AS ROW_PROCESS_DTM,
			--:audit_id AS AUDIT_ID,
			FALSE 													AS LOGICAL_DELETE_IND,
			FALSE 													AS CURRENT_ROW_IND,
			CURRENT_DATE        									AS END_DT,
			CURRENT_TIMESTAMP(6)         							AS END_DTM,
			'47' 													AS SOURCE_SYSTEM_ID, 
			FALSE 													AS RESTRICTED_ROW_IND, 
			--:audit_id as UPDATE_AUDIT_ID, 
			UUID_GEN(NULL)::UUID 									AS DIM_ADDRESS_NATURAL_KEY_HASH_UUID, 
			NULL 													AS ADDRESS_TYPE_CDE, 
			NULL 													AS ATTENTION_LINE_TXT, 
			UUID_GEN((NULL))::UUID                               	AS DIM_PHONE_NATURAL_KEY_HASH_UUID,
			UUID_GEN((NULL))::UUID                        		 	AS DIM_ELECTRONIC_ADDRESS_NATURAL_KEY_HASH_UUID,
			UUID_GEN((NULL))::UUID                               	AS DIM_PARTY_AKA_NAME_NATURAL_KEY_HASH_UUID,
			UUID_GEN((NULL))::UUID                               	AS ADVISOR_DIM_SELLING_AGREEMENT_NATURAL_KEY_HASH_UUID,
			UUID_GEN((NULL))::UUID                               	AS FIRM_DIM_SELLING_AGREEMENT_NATURAL_KEY_HASH_UUID,
			UUID_GEN((NULL))::UUID									AS AGENCY_DIM_PARTY_NATURAL_KEY_HASH_UUID,
			UUID_GEN((NULL))::UUID									AS DISTRIBUTOR_DIM_PARTY_NATURAL_KEY_HASH_UUID,
			NULL 												 	AS SOURCE_PARTY_ROLE_CDE, 
			NULL 													AS SOURCE_PARTY_SUB_ROLE_CDE, 
			NULL 													AS SOURCE_ADDRESS_TYPE_CDE, 
			TRUE                                                    AS SOURCE_DELETE_IND,  
			NULL 													AS BENEFICIARY_ISS_PER_STIRPES_CDE, 
			REL_START_DATE::DATE 									AS BUSINESS_STRT_DT, 
			REL_END_DATE::DATE 										AS BUSINESS_END_DT 
			from edw_staging.pdcr_rel_edw_td_pdcr_agrl_snapshot PD 
				LEFT JOIN 
				(    
				SELECT MEMBER_ID,SRC_SYS_ID FROM edw_staging.amdm_advsr_member_id_xref_out_snapshot 
				WHERE SRC_SYS = 'FSBP' AND add_upd_del_ind <> 'D'
				) T1
				on coalesce(btrim(T1.src_sys_id),'') = coalesce(btrim(PD.SRC_ID),'')
			--WHERE CLEAN_STRING(CARR_ADMN_SYS_CD)<> 'Combnd' AND SOURCE_SYSTEM_ID= '47'  AND REGEXP_NOT_LIKE(HLDG_KEY,'-')
			where COALESCE(PD.HUB_STATE_IND,1) < 0 
			)Q_1
		)Q_2;
	
COMMIT;

SELECT COUNT(*) FROM TEMP_PDCR_REL_REL_PARTY_AGREEMENT WHERE CURRENT_ROW_IND; --20002036

DROP TABLE IF EXISTS PRE_WORK;

CREATE LOCAL TEMPORARY TABLE PRE_WORK ON COMMIT PRESERVE ROWS AS 
SELECT * FROM TEMP_PDCR_REL_REL_PARTY_AGREEMENT WHERE 1<>1;
/*inserting records into the prework table for taking from the temp table*/	

INSERT INTO PRE_WORK
(	
	CARR_ADMN_SYS_CD,
	DIM_AGREEMENT_NATURAL_KEY_HASH_UUID, 
	DIM_PARTY_NATURAL_KEY_HASH_UUID, 
	REF_PARTY_ROLE_NATURAL_KEY_HASH_UUID, 
	REF_PARTY_SUB_ROLE_NATURAL_KEY_HASH_UUID, 
	DIM_ACCOUNT_NATURAL_KEY_HASH_UUID, 
	BEGIN_DT, 
	BEGIN_DTM, 
	ROW_PROCESS_DTM, 
	--AUDIT_ID, 
	LOGICAL_DELETE_IND, 
	CHECK_SUM, 
	CURRENT_ROW_IND, 
	END_DT, 
	END_DTM, 
	SOURCE_SYSTEM_ID, 
	RESTRICTED_ROW_IND, 
	--UPDATE_AUDIT_ID, 
	DIM_ADDRESS_NATURAL_KEY_HASH_UUID, 
	ADDRESS_TYPE_CDE, 
	ATTENTION_LINE_TXT, 
	DIM_PHONE_NATURAL_KEY_HASH_UUID, 
	DIM_ELECTRONIC_ADDRESS_NATURAL_KEY_HASH_UUID, 
	DIM_PARTY_AKA_NAME_NATURAL_KEY_HASH_UUID,  
	ADVISOR_DIM_SELLING_AGREEMENT_NATURAL_KEY_HASH_UUID,
	FIRM_DIM_SELLING_AGREEMENT_NATURAL_KEY_HASH_UUID,
	AGENCY_DIM_PARTY_NATURAL_KEY_HASH_UUID,
	DISTRIBUTOR_DIM_PARTY_NATURAL_KEY_HASH_UUID,
	SOURCE_PARTY_ROLE_CDE, 
	SOURCE_PARTY_SUB_ROLE_CDE, 
	SOURCE_ADDRESS_TYPE_CDE, 
	SOURCE_DELETE_IND, 
	beneficiary_ISS_per_stirpes_cde, 
	business_strt_dt, 
	business_end_dt)
SELECT 
	CARR_ADMN_SYS_CD,
	DIM_AGREEMENT_NATURAL_KEY_HASH_UUID, 
	DIM_PARTY_NATURAL_KEY_HASH_UUID, 
	REF_PARTY_ROLE_NATURAL_KEY_HASH_UUID, 
	REF_PARTY_SUB_ROLE_NATURAL_KEY_HASH_UUID, 
	DIM_ACCOUNT_NATURAL_KEY_HASH_UUID, 
	BEGIN_DT, 
	BEGIN_DTM, 
	ROW_PROCESS_DTM, 
	--:audit_id as audit_id, 
	LOGICAL_DELETE_IND, 
	CHECK_SUM, 
	CURRENT_ROW_IND, 
	END_DT, 
	END_DTM, 
	SOURCE_SYSTEM_ID, 
	RESTRICTED_ROW_IND, 
	--:audit_id as UPDATE_AUDIT_ID, 
	DIM_ADDRESS_NATURAL_KEY_HASH_UUID, 
	ADDRESS_TYPE_CDE, 
	ATTENTION_LINE_TXT, 
	DIM_PHONE_NATURAL_KEY_HASH_UUID, 
	DIM_ELECTRONIC_ADDRESS_NATURAL_KEY_HASH_UUID, 
	DIM_PARTY_AKA_NAME_NATURAL_KEY_HASH_UUID, 
	ADVISOR_DIM_SELLING_AGREEMENT_NATURAL_KEY_HASH_UUID,
	FIRM_DIM_SELLING_AGREEMENT_NATURAL_KEY_HASH_UUID,
	AGENCY_DIM_PARTY_NATURAL_KEY_HASH_UUID,
	DISTRIBUTOR_DIM_PARTY_NATURAL_KEY_HASH_UUID,
	SOURCE_PARTY_ROLE_CDE, 
	SOURCE_PARTY_SUB_ROLE_CDE, 
	SOURCE_ADDRESS_TYPE_CDE, 
	SOURCE_DELETE_IND, 
	beneficiary_ISS_per_stirpes_cde, 
	business_strt_dt, 
	business_end_dt
	FROM 
	(
	SELECT A.*,
	ROW_NUMBER() OVER(PARTITION BY DIM_AGREEMENT_NATURAL_KEY_HASH_UUID,
	DIM_PARTY_NATURAL_KEY_HASH_UUID,REF_PARTY_ROLE_NATURAL_KEY_HASH_UUID,REF_PARTY_SUB_ROLE_NATURAL_KEY_HASH_UUID ORDER BY business_strt_dt DESC) AS RNK
	FROM TEMP_PDCR_REL_REL_PARTY_AGREEMENT as A 
	) Q 
	WHERE RNK = 1;

COMMIT;

select count(*) from pre_work where current_row_ind and source_system_id = '47';--19790175

select count(*) from edw_vw.rel_party_agreement_vw where current_row_ind and source_system_id='47';--1076351

select distinct source_system_id from TEMP_PDCR_REL_REL_PARTY_AGREEMENT;