DROP TABLE edw_work.party_cdavntg1life_rel_party_agreement CASCADE;



CREATE TABLE edw_work.party_cdavntg1life_rel_party_agreement
(
    dim_agreement_natural_key_hash_uuid uuid NOT NULL,
    dim_party_natural_key_hash_uuid uuid NOT NULL,
    ref_party_role_natural_key_hash_uuid uuid,
    ref_party_sub_role_natural_key_hash_uuid uuid,
    dim_account_natural_key_hash_uuid uuid,
    begin_dt date NOT NULL DEFAULT '0001-01-01'::date,
    begin_dtm timestamp(6) NOT NULL DEFAULT '0001-01-01 00:00:00'::timestamp,
    row_process_dtm timestamp(6) NOT NULL DEFAULT now(),
    audit_id int NOT NULL DEFAULT 0,
    logical_delete_ind boolean NOT NULL DEFAULT false,
    check_sum uuid NOT NULL,
    current_row_ind boolean NOT NULL DEFAULT true,
    end_dt date NOT NULL DEFAULT '9999-12-31'::date,
    end_dtm timestamp(6) NOT NULL DEFAULT '9999-12-31 23:59:59.999999'::timestamp,
    source_system_id varchar(50) NOT NULL,
    restricted_row_ind boolean NOT NULL DEFAULT false,
    row_sid  IDENTITY ,
    update_audit_id int NOT NULL DEFAULT 0,
    dim_address_natural_key_hash_uuid uuid,
    address_type_cde varchar(50),
    attention_line_txt varchar(100),
    dim_phone_natural_key_hash_uuid uuid,
    dim_electronic_address_natural_key_hash_uuid uuid,
    dim_party_aka_name_natural_key_hash_uuid uuid,
    beneficiary_sub_class_nr int,
    beneficiary_relationship_nm varchar(200),
    beneficiary_allocation_pct numeric(9,6),
    beneficiary_allocation_amt numeric(17,4),
    beneficiary_agreement_txt varchar(500),
    source_party_role_cde varchar(50),
    source_party_sub_role_cde varchar(50),
    source_address_type_cde varchar(50),
    source_delete_ind boolean NOT NULL DEFAULT false,
    beneficiary_ISS_per_stirpes_cde varchar(50),
    business_strt_dt date,
    business_end_dt date,
    advisor_first_year_commission numeric(9,3),
    advisor_renewal_commission numeric(6,3),
    advisor_dim_selling_agreement_natural_key_hash_uuid uuid,
    firm_dim_selling_agreement_natural_key_hash_uuid uuid,
    solicit_writing_agent_ind boolean,
    service_agent_ind boolean,
    career_corporation_ind boolean,
    source_package_id varchar(50),
    source_status_cde varchar(50),
    source_status_reason_cde varchar(50),
    agreement_distribution_channel_cde varchar(50),
    advisor_order_nr int,
    agency_dim_party_natural_key_hash_uuid uuid,
    advisor_commission_pct numeric(3,0),
    beneficiary_role_position_cde varchar(50),
    source_beneficiary_role_cde varchar(50),
    source_beneficiary_role_position_cde varchar(50),
    beneficiary_role_sequence_nr int,
    source_beneficiary_role_sequence_nr int,
    beneficiary_effective_dt date,
    beneficiary_trust_dt date,
    beneficiary_special_destination_cde varchar(50),
    beneficiary_row_control_cde varchar(50),
    beneficiary_destination_amt numeric(17,4),
    source_party_id varchar(50),
    source_alternate_party_id varchar(50),
    source_agent_writing_agency_cde varchar(50),
    source_agent_writing_agency_id varchar(50),
    distributor_dim_party_natural_key_hash_uuid uuid,
    beneficiary_class_cde varchar(50),
    beneficiary_designation_txt varchar(50),
    beneficiary_name_format_cde varchar(50),
    beneficiary_role_sequence_nr_txt varchar(50),
    source_beneficiary_role_sequence_nr_txt varchar(50),
    beneficiary_sub_class_cde varchar(50),
    beneficiary_unformatted_nm varchar(200)
);



SELECT MARK_DESIGN_KSAFE(1);
